[vcfanno.ui.sections]
order = ["readfiles"]
[vcfanno.ui.sections.ui_basic]
readfiles = "title = 'Input files', status = 'primary', width = 12, collapsed = FALSE, collapsible = TRUE"

[vcfanno.paramters.readfiles]
# For reading vcfannoR shiny APP vcfanno tool input files  
section_type = "input"
rcmd_last = """
if (in_text != "") {
  in_file = tempfile()
  cat(in_text, file = in_file)
}
out_key <- qqkey

shiny_config <- Sys.getenv("BIOSHINY_CONFIG", system.file("extdata", "config/shiny.config.yaml",
                                                  package = "bioshiny"))
config <- configr::read.config(shiny_config)

db_dir = normalizePath(config$shiny_download$download_dir, mustWork = FALSE)

annovarR::annotation(anno.name = "vcfanno_demo", input.file = in_file, buildver = in_reffa, 
                     database.dir = db_dir, 
                     vcfanno = normalizePath(config$shiny_tools_path$vcfanno, mustWork = FALSE), 
                     out = sprintf("%s/output/%s/%s.vcf", dirname(config$shiny_db$db_path), out_key, basename(in_file))
                    )
"""
progressbar_message = ""
render_id = "vcfanno_readfiles"

#!!!!! input_ui_order required related section
input_ui_order = ["single_input", "start_analysis"]

[vcfanno.paramters.readfiles.input.single_input]
title = "Demo input:"
title_control = "class = 'input-section-p'"
varname = ["in_file", "in_text", "in_reffa", "in_config"]
input_id = ["vcfanno_input_file", "vcfanno_input_file_area", "vcfanno_input_file_genome", 
"vcfanno_config"]
type = ["shiny::selectInput", "shiny::textAreaInput", "shiny::selectInput", "shiny::selectInput"]
label = ["Input File (in_file)", "or Paste Variant Calls (in_text)", "Reference Genome (in_reffa)", "vcfanno configuration file (in_config)"]
[vcfanno.paramters.readfiles.input.single_input.choices] 
in_file = "!!glue {c(system.file('extdata', 'demo/vcfanno_demo/query.vcf.gz', package = 'annovarR'), featch_files()$file_path)}"
in_reffa = ["hg19", "hg38", "mm9", "mm10"]
in_config = "!!glue {c(system.file('extdata', 'demo/vcfanno_demo/conf.toml', package = 'annovarR'), featch_files('toml')$file_path)}"
[vcfanno.paramters.readfiles.input.single_input.selected] 
in_file = "@>@system.file('extdata', 'demo/vcfanno_demo/query.vcf.gz', package = 'annovarR')@<@"
in_reffa = "hg19"
[vcfanno.paramters.readfiles.input.single_input.rows]
in_text = 15

[vcfanno.paramters.readfiles.input.start_analysis]
input_id = "start_vcfanno_analysis"
type = "shiny::actionButton"
label = "Submit"
