[annovarR.ui.sections]
order = ["readfiles"]
[annovarR.ui.sections.ui_basic]
readfiles = "title = 'Input files', status = 'primary', width = 12, collapsed = FALSE, collapsible = TRUE"

[annovarR.paramters.readfiles]
# For reading annovarRR shiny APP annovarR tool input files  
section_type = "input"
rcmd_last = """
if (in_text != "") {
  in_text <- stringr::str_replace(in_text, " +", " ")
  in_file = tempfile()
  cat(in_text, file = in_file)
}
input.dat <- data.table::fread(in_file)
if (ncol(input.dat)>5)
  input.dat <- input.dat[,1:5]
out_key <- qqkey

out = sprintf("~/.annovarR/output/%s/%s.Rdata", out_key, basename(in_file))
dir.create(dirname(out), recursive = TRUE)

result <- annovarR::annotation.merge(dat = input.dat, anno.name = in_anno_names,
buildver = in_reffa, database.dir = '@>@db_dir@<@', 
vcfanno = '@>@normalizePath(annovarR_shiny_tools_path$vcfanno, mustWork = FALSE)@<@', 
annovar.dir = '@>@normalizePath(annovarR_shiny_tools_path$annovar, mustWork = FALSE)@<@')
save(result, file = out)
"""
progressbar_message = ""
render_id = "annovarR_readfiles"

#!!!!! input_ui_order required related section
input_ui_order = ["single_input", "start_analysis"]

[annovarR.paramters.readfiles.input.single_input]
title = "Demo input:"
title_control = "class = 'input-section-p'"
varname = ["in_file", "in_text", "in_reffa", 
"in_file_type", "in_anno_names"]
input_id = ["annovarR_input_file", "annovarR_input_file_area", "annovarR_input_file_genome", 
"annovarR_input_file_type", "annovarR_input_annotation_items"]
type = ["shiny::selectInput", "shiny::textAreaInput", "shiny::selectInput", 
"shiny::selectInput", "shiny::selectInput"]
label = ["Input File (in_file)", "or Paste Variant Calls (in_text)", "Reference Genome (in_reffa)", 
"Input Format (in_file_type)", "Annotaion Databases (in_anno_names)"]
[annovarR.paramters.readfiles.input.single_input.choices] 
in_file = "!!glue {featch_files()$file_path}"
in_reffa = ["hg19", "hg38", "mm9", "mm10"]
in_file_type = ["vcf", "vcf_old", "tsv", "avinput", "solid_gff3", "complete_genomics_masterVar"]
in_anno_names = "!!glue {c('annovar_all', annovarR_annotation_names)}"
[annovarR.paramters.readfiles.input.single_input.selected] 
in_reffa = "hg19"
in_file_type = "avinput"
in_anno_names = "all"
[annovarR.paramters.readfiles.input.single_input.multiple]
in_anno_names = true
[annovarR.paramters.readfiles.input.single_input.rows]
in_text = 15

[annovarR.paramters.readfiles.input.start_analysis]
input_id = "start_annovarR_analysis"
type = "shiny::actionButton"
label = "Submit"
